# docker-compose.yml
version: "3.8"

services:
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "6379:6379"
    restart: unless-stopped

  letterboxd-api:
    build: .
    image: saisamarth21/letterboxd-api:latest
    ports:
      - "6996:6996"
    environment:
      REDIS_URL: "redis://redis:6379/0"
    depends_on:
      - redis
    restart: unless-stopped
